### ISSUE TITLE
Can't change icon color

### ISSUE THREAD

**Issue by FastThenLeft** [antoniocoratelli/bookmarks-indicator#4]
Using Ubuntu 16.04.  No matter what values I use after the -i option, the icon color never changes.

**Comment by antoniocoratelli** [comment]
Hi @FastThenLeft ,
please after line 236 in `bookmarks-indicator.py`:

```
    indicator_icon = indicator_icon.replace("####", str(args.color))
```

add:

```
    print str(args.color)
    print indicator_icon
```

and paste here the output

**Comment by antoniocoratelli** [comment]
do you use quotes and `#` symbol when you pass hex colors to arg `-i`?

for example, these options are ok:
- `bookmarks-indicator.py -i "#FF0000"` -- html hex color should be recognized
- `bookmarks-indicator.py -i "red"` -- html color word should be recognized

these are not:
- `bookmarks-indicator.py -i #FF0000` -- without quotes `#` symbol is interpreted as comment in bash shell
- `bookmarks-indicator.py -i "FF0000"` -- html hex color won't be recognized

**Comment by antoniocoratelli** [comment]
Hi @FastThenLeft , please could you give me some feedback for the issue? I can't reproduce the bug since I'm on _trusty_ (will update to the latest LTS in a couple of months).
Thank you,
Antonio

**Comment by FastThenLeft** [comment]
Antonio-
- bookmarks-indicator.py -i "#FF0000"
- bookmarks-indicator.py -i "red"

Works!  Thanks!

I had tried:
bookmarks-indicator.py -i #FF0000
and got an error.  So I tried:
bookmarks-indicator.py -i FF0000
and did not get an error, but the icon did not change, so I thought it was broken.  I guess it was not obvious to me that it needed to be quoted.  Also, you might mention that you can actually use the html color word too.

**Comment by antoniocoratelli** [comment]
Thanks for the feedback!
I updated README and Help to state it more clearly (commit 52d53e455253a94919ad69357e7348ea678e3a10)

Thank you :smile:
