### ISSUE TITLE
Not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by lesar** [antoniocoratelli/bookmarks-indicator#5]
Hallo Antonio thanks for this app.  
in Ubuntu 19.10 wont work.  
(I have clone the repo)  
can you please write the prerequisite installation more exactly.  
Like:  
`$ pip3 os os-sys` and so on  
or  
`$ sudo apt install python3-sys` ... 
I'm new to python :-) 
Thanks you

**Comment by antoniocoratelli** [comment]
Hi lesar, can you describe what is the error message you have running the indicator on Ubuntu 19.10?

**Comment by lesar** [comment]
To get error I have start the app on terminal.  
At startup show this:  
```
home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py -i "#ffcc00"
/home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:128: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item = gtk.MenuItem(name, False)
/home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:90: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  l = gtk.MenuItem("GitHub")
/home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:91: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  r = gtk.MenuItem("Restart")
/home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:92: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  q = gtk.MenuItem("Quit")
```

Then I try to open a bookmark:  
Noting show and no error output on terminal.  

If you have a best manner to get error let me know:
any log etc. ...

best regards,
Leonardo

**Comment by antoniocoratelli** [comment]
Check if you have `xdg-open` on your system: run `xdg-open /` in a shell. If you have something like "xdg-open command not found", then do a `sudo apt install xdg-utils`

**Comment by lesar** [comment]
I have xdg-open and xdg-utils.  
```
$ sudo apt policy xdg-utils
[sudo] password di leonardo: 
xdg-utils:
  Installato: 1.1.3-1ubuntu2
  Candidato:  1.1.3-1ubuntu2
  Tabella versione:
 *** 1.1.3-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu eoan/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by antoniocoratelli** [comment]
Ciao leonardo,

try `issue-5` branch and tell me what is the log that you see in the terminal please :)

**Comment by lesar** [comment]
sorry but do not understand: issue-5 is this or not is this? :-)  
can you out a link?

**Comment by antoniocoratelli** [comment]
go in the folder where you cloned the repository and do a `git checkout issue-5`

**Comment by lesar** [comment]
Ops! Sorry I haven't understood that you have create a branch named issue-5.  
but if I check by   `git branch -a` it give me:  

> * master
>   remotes/origin/HEAD -> origin/master
>   remotes/origin/master

and so if I try:
`git checkout issue-5` it give me:  

> error: pathspec 'issue-5' did not match any file(s) known to git

Sure I have do something wrong.

## Update
I have to do `git fetch` and then  `git checkout issue-5`

I try and have the same result:  
`$ /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py -i "#ffcc00"`

> /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:128: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
>   item = gtk.MenuItem(name, False)
> /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:90: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
>   l = gtk.MenuItem("GitHub")
> /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:91: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
>   r = gtk.MenuItem("Restart")
> /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.py:92: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
>   q = gtk.MenuItem("Quit")

`$ python -V` 

> Python 2.7.17rc1

`$ python3 -V`

> Python 3.7.5rc1

**Comment by antoniocoratelli** [comment]
Try to click on an element to open it, it should show some log

**Comment by lesar** [comment]
Yes I have do, but there isn't new message on terminal and nothing open at screen.  
First click show my path.  
If I click on a path do nothing.

**Comment by antoniocoratelli** [comment]
can you please send me a screencast of what you do step by step?

**Comment by lesar** [comment]
Do it: you can download from [qui](https://send.firefox.com/download/bec4f0b283a1f528/#ocdntQ71zASjSepZUDoXAQ)  
The first to download stop download ability or after 7 days.  
You can see my click and the terminal.  
best regards,  
Leonardo

**Comment by antoniocoratelli** [comment]
ok, so it seems that there's an issue either in detecting the "hover" event in the gui, or when the program tries to detect the content of a folder. are you sure that `CurrentManual` and `manuali` exist?

paste here the content of yout `config` file please

**Comment by lesar** [comment]
yes:  
`$ cat config`   

> /home/leonardo/sviluppo/documentazione/CurrentManual
> /home/leonardo/sviluppo/documentazione/manuali

`$ ls /home/leonardo/sviluppo/documentazione/CurrentManual`

> argo                  database    hsqldb                 java        MikroTik-RouterOSTM-v3.0.pdf  nag2.pdf               proGit.pdf          recoll_user_manual.pdf  salt
> beginningBlender.pdf  freepascal  ispconfig3_manual.pdf  javascript  mybatis                       netbeansPlatform7.pdf  programma-5-stelle  rrb

`$ ls /home/leonardo/sviluppo/documentazione/manuali`

> android  burraco  database  freepascal  git      html       java        laravel  linux       netbeans  provisioning  regione-toscana     repeater  sj4  up.sh
> arduino  css      down.sh   front-end   grafica  ISPConfig  javascript  ldap     matematica  php       python        regular-expression  routing   uml

**Comment by antoniocoratelli** [comment]
ok, so it's a gui issue

do a `git pull origin issue-5` and try again

**Comment by lesar** [comment]
do but same result.  
sorry

**Comment by antoniocoratelli** [comment]
add

```
/home/leonardo/sviluppo/documentazione/CurrentManual/proGit.pdf
```
at the end of `config` and check if you can at least open this file directly

**Comment by lesar** [comment]
yes it is been open  
so was directory the problem

**Comment by antoniocoratelli** [comment]
ok, so the issue is limited to the submenus

I did another change, do a `git pull origin issue-5` again and check folders/files opening

**Comment by lesar** [comment]
ok have try but same result

**Comment by antoniocoratelli** [comment]
I see... I think it's an issue of the gtk menu item in gnome. unfortunately I am not on ubuntu anymore, so I can't debug the issue.

Have a look at the "Signals" sections of these pages:
- https://developer.gnome.org/pygtk/stable/class-gtkmenuitem.html
- https://developer.gnome.org/pygtk/stable/class-gtkitem.html
- https://developer.gnome.org/pygtk/stable/class-gtkwidget.html

and try to change line 130 of `bookmarks-indicator.py` to:
```
item.connect("SIGNAL-NAME-HERE", self.onhover, path, submenu)
```

with some signal names that look appropriate to you

if you find a solution let me know!

**Comment by lesar** [comment]
I try `set_events (Gdk.EventMask.BUTTON_PRESS_MASK)` but nothing  
then I try using 'activate' but nothing.   
sorry

**Comment by antoniocoratelli** [comment]
Ciao lesar,

ho provato a riscrivere il programma in C++, puoi provarlo sul branch `rewrite-cpp`. Bisogna compilarlo manualmente utilizzando cmake e make. È ancora in fase beta (ci sono un paio di bug da fixare e funzionalità da aggiungere ancora), ma magari può risolvere il problema con il click sul  menù iniziale. Fammi sapere se funziona, Buona giornata :)

**Comment by lesar** [comment]
Ciao Antonio:

$ cmake .
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtkmm-3.0'
--   No package 'gtkmm-3.0' found
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452
(message): A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622
(_pkg_check_modules_internal) CMakeLists.txt:6 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also
"/home/leonardo/bookmarks-indicator-master/bookmarks-indicator/CMakeFiles/CMakeOutput.log".


Il fatto che manchi gtkmm potrebbe indicare anche il motivo del
fallimento della versione python?

Saluti,
Leonardo

On Sun, 10 Nov 2019 01:59:53 -0800
Antonio Coratelli <notifications@github.com> wrote:

> Ciao lesar,
> 
> ho provato a riscrivere il programma in C++, puoi provarlo sul branch
> `rewrite-cpp`. Bisogna compilarlo manualmente utilizzando cmake e
> make. È ancora in fase beta (ci sono un paio di bug da fixare e
> funzionalità da aggiungere ancora), ma magari può risolvere il
> problema con il click sul  menù iniziale. Fammi sapere se funziona,
> Buona giornata :)
> 



-- 
dott. Leonardo Saracini
Tel.: +39 055-8259606
cell.: +39 3393770697

**Comment by antoniocoratelli** [comment]
Installa le dipendenze con

sudo apt-get install build-essential libgtk-3-dev

credo ci sia anche una libreria dal nome simile a libgtkmm-3-dev da installare

**Comment by lesar** [comment]
fatto e compilato con 
cmake .
make 
:
...
[100%] Linking CXX executable bookmarks-indicator
[100%] Built target bookmarks-indicator

ma quando provo ad eseguirlo:
./bookmarks-indicator

parte, resta in esecuzione ma non fa niente ne da messaggi di sorta.


On Mon, 11 Nov 2019 10:11:36 -0800
Antonio Coratelli <notifications@github.com> wrote:

> Installa le dipendenze con
> 
> sudo apt-get install build-essential libgtk-3-dev
> 
> credo ci sia anche una libreria dal nome simile a libgtkmm-3-dev da
> installare
> 



-- 
dott. Leonardo Saracini
Tel.: +39 055-8259606
cell.: +39 3393770697

**Comment by antoniocoratelli** [comment]
Non appare niente nella barra di notifica? In alcuni desktop environment
l'icona compare nella barra secondaria invece di quella primaria

**Comment by antoniocoratelli** [comment]
Ciao lesar,

ho terminato la riscrittura in C++ dell'indicator, cancella la cartella precedente e re-installa il programma seguendo le indicazioni nel README per favore. Ho aggiunto altro output di debug, fammi sapere se questo risolve il tuo problema.

Buona giornata!

**Comment by lesar** [comment]
sorry.  
```bash
leonardo@leon:$ cd bookmarks-indicator/build
leonardo@leon:$ cmake .. && make && sudo make install 
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtkmm-3.0'
--   Found gtkmm-3.0, version 3.24.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/build
Scanning dependencies of target bookmarks-indicator
[ 50%] Building CXX object CMakeFiles/bookmarks-indicator.dir/bookmarks-indicator.cpp.o
In file included from /usr/include/pangomm-1.4/pangomm/context.h:31,
                 from /usr/include/gtkmm-3.0/gtkmm/widget.h:31,
                 from /usr/include/gtkmm-3.0/gtkmm/misc.h:27,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:27,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glibmm-2.4/glibmm/object.h:73:15: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
   73 |   GParameter* parameters;
      |               ^~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glibmm-2.4/glibmm/class.h:24,
                 from /usr/include/glibmm-2.4/glibmm/objectbase.h:21,
                 from /usr/include/glibmm-2.4/glibmm/object.h:29,
                 from /usr/include/pangomm-1.4/pangomm/context.h:31,
                 from /usr/include/gtkmm-3.0/gtkmm/widget.h:31,
                 from /usr/include/gtkmm-3.0/gtkmm/misc.h:27,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:27,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glib-2.0/gobject/gparam.h:194:28: note: declared here
  194 | typedef struct _GParameter GParameter GLIB_DEPRECATED_TYPE_IN_2_54;
      |                            ^~~~~~~~~~
In file included from /usr/include/gdkmm-3.0/gdkmm/pixbufanimationiter.h:29,
                 from /usr/include/gdkmm-3.0/gdkmm/pixbufanimation.h:29,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:29,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glibmm-2.4/glibmm/timeval.h:38:42: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   38 |   inline TimeVal(const GTimeVal& gtimeval);
      |                                          ^
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glibmm-2.4/glibmm/unicode.h:23,
                 from /usr/include/glibmm-2.4/glibmm/ustring.h:21,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:6,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glib-2.0/glib/gtypes.h:549:26: note: declared here
  549 | typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
      |                          ^~~~~~~~
In file included from /usr/include/gdkmm-3.0/gdkmm/pixbufanimationiter.h:29,
                 from /usr/include/gdkmm-3.0/gdkmm/pixbufanimation.h:29,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:29,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glibmm-2.4/glibmm/timeval.h:39:53: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   39 |   inline TimeVal& operator=(const GTimeVal& gtimeval);
      |                                                     ^
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glibmm-2.4/glibmm/unicode.h:23,
                 from /usr/include/glibmm-2.4/glibmm/ustring.h:21,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:6,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glib-2.0/glib/gtypes.h:549:26: note: declared here
  549 | typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
      |                          ^~~~~~~~
In file included from /usr/include/gdkmm-3.0/gdkmm/pixbufanimationiter.h:29,
                 from /usr/include/gdkmm-3.0/gdkmm/pixbufanimation.h:29,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:29,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glibmm-2.4/glibmm/timeval.h:104:49: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
  104 | inline TimeVal::TimeVal(const GTimeVal& gtimeval)
      |                                                 ^
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glibmm-2.4/glibmm/unicode.h:23,
                 from /usr/include/glibmm-2.4/glibmm/ustring.h:21,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:6,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glib-2.0/glib/gtypes.h:549:26: note: declared here
  549 | typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
      |                          ^~~~~~~~
In file included from /usr/include/gdkmm-3.0/gdkmm/pixbufanimationiter.h:29,
                 from /usr/include/gdkmm-3.0/gdkmm/pixbufanimation.h:29,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:29,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glibmm-2.4/glibmm/timeval.h:111:44: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
  111 | TimeVal::operator=(const GTimeVal& gtimeval)
      |                                            ^
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glibmm-2.4/glibmm/unicode.h:23,
                 from /usr/include/glibmm-2.4/glibmm/ustring.h:21,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:6,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glib-2.0/glib/gtypes.h:549:26: note: declared here
  549 | typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
      |                          ^~~~~~~~
In file included from /usr/include/gtkmm-3.0/gtkmm/image.h:29,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/gdkmm-3.0/gdkmm/pixbufanimation.h:184:72: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
  184 |   Glib::RefPtr<PixbufAnimationIter> get_iter(const GTimeVal* start_time);
      |                                                                        ^
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glibmm-2.4/glibmm/unicode.h:23,
                 from /usr/include/glibmm-2.4/glibmm/ustring.h:21,
                 from /usr/include/gtkmm-3.0/gtkmm/image.h:6,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MenuItemBase.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/include/bkm/MainWindow.h:19,
                 from /home/leonardo/bookmarks-indicator-master/bookmarks-indicator/bookmarks-indicator.cpp:17:
/usr/include/glib-2.0/glib/gtypes.h:549:26: note: declared here
  549 | typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
      |                          ^~~~~~~~
[100%] Linking CXX executable bookmarks-indicator
[100%] Built target bookmarks-indicator
[100%] Built target bookmarks-indicator
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/bookmarks-indicator
```

```bash
leonardo@leon:$ /usr/local/bin/bookmarks-indicator -i "#ffcc00"
>>> Add bkm::MenuItemFolderContent(/home/leonardo/sviluppo/documentazione/manuali)
>>> Add bkm::SeparatorMenuItem
>>> Add bkm::MenuItemGitHub
>>> Add bkm::MenuItemQuit
Ready!
```

The process is live but no icon is show  

![immagine](https://user-images.githubusercontent.com/6347403/69624520-22272500-1045-11ea-85ba-a370f78362bc.png)

best regards,
Leonardo

P.S. you can use docker to develop end test:  
you can get an ubuntu image from [hub](https://hub.docker.com/) or best you can make  it by `deboostrap`.  
If you choose `deboostrap` then you can chrooted into the new ubuntu vm folder, install **vnc server** and **ubuntu desktop**.  

Then use it to make a docker image.  

Make a docker config file to install all dep. (so you can change it without rebuilt the image)

Then you can start it in a container using your app current directory on your host as a doker volume giving it the command to compile your app and then start an interactive docker terminal.  

In the terminal you can start your app and, on host machine(your s.o.), you can see on a vnc client the desktop to check the graph and in docker terminal you can see log etc.  

It is not hard to do and you can test it easy.

**Comment by antoniocoratelli** [comment]
ok, so last test for you, if it doesn't work I'll setup a test environment on my machine with ubuntu: follow this solution https://askubuntu.com/a/1058682

**Comment by lesar** [comment]
Antonio i can do other test but It Is more usefull try a solution using an
Ubuntu env on developer machine so you can do test more quicly

Il mar 26 nov 2019, 16:08 Antonio Coratelli <notifications@github.com> ha
scritto:

**Comment by antoniocoratelli** [comment]
Esegui `sudo apt-get install libappindicator-dev gnome-tweak-tool gnome-tweaks gnome-shell-extension-appindicator`

Installa l'estensione gnome:
https://github.com/phocean/TopIcons-plus
(segui le istruzioni nel readme, devi fare un `git clone` poi `make install`)

Esegui `gnome-shell-extension-prefs`, nella barra della finestra, vicino ai tasti per chiudere e minimizzare la finestra c'è uno slider, mettilo su on (diventa verde)

Attiva "TopIcons Plus"

Fai logout e poi login

apri un terminale, esegui `bookmarks-indicator -i folder`, dovresti vedere apparire un'icona accanto alla data del sistema.

Fammi sapere se va

**Comment by lesar** [comment]
Before do a test I have a problem:  
**libappindicator-install** is missing so I try:  

`$ sudo apt policy libappindicator*`  

> libappindicator3-0.1-cil:
>   Installato: (nessuno)
>   Candidato:  12.10.0+git20151221-5
>   Tabella versione:
>      12.10.0+git20151221-5 500
>         500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
> libappindicator0.1-cil-dev:
>   Installato: (nessuno)
>   Candidato:  12.10.1+18.04.20180322.1-0ubuntu4
>   Tabella versione:
>      12.10.1+18.04.20180322.1-0ubuntu4 500
>         500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
>         500 http://archive.ubuntu.com/ubuntu eoan/universe i386 Packages
> libappindicator-dev:
>   Installato: (nessuno)
>   Candidato:  12.10.1+18.04.20180322.1-0ubuntu4
>   Tabella versione:
>      12.10.1+18.04.20180322.1-0ubuntu4 500
>         500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
> libappindicator-doc:
>   Installato: (nessuno)
>   Candidato:  12.10.1+18.04.20180322.1-0ubuntu4
>   Tabella versione:
>      12.10.1+18.04.20180322.1-0ubuntu4 500
>         500 http://archive.ubuntu.com/ubuntu eoan/main amd64 Packages
>         500 http://archive.ubuntu.com/ubuntu eoan/main i386 Packages
> libappindicator0.1-cil:
>   Installato: 12.10.1+18.04.20180322.1-0ubuntu4
>   Candidato:  12.10.1+18.04.20180322.1-0ubuntu4
>   Tabella versione:
>  *** 12.10.1+18.04.20180322.1-0ubuntu4 500
>         500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
>         500 http://archive.ubuntu.com/ubuntu eoan/universe i386 Packages
>         100 /var/lib/dpkg/status
> libappindicator3-1:
>   Installato: 12.10.1+18.04.20180322.1-0ubuntu4
>   Candidato:  12.10.1+18.04.20180322.1-0ubuntu4
>   Tabella versione:
>  *** 12.10.1+18.04.20180322.1-0ubuntu4 500
>         500 http://archive.ubuntu.com/ubuntu eoan/main amd64 Packages
>         100 /var/lib/dpkg/status
> libappindicator1:
>   Installato: 12.10.1+18.04.20180322.1-0ubuntu4
>   Candidato:  12.10.1+18.04.20180322.1-0ubuntu4
>   Tabella versione:
>  *** 12.10.1+18.04.20180322.1-0ubuntu4 500
>         500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
>         100 /var/lib/dpkg/status
> libappindicator3-dev:
>   Installato: (nessuno)
>   Candidato:  12.10.1+18.04.20180322.1-0ubuntu4
>   Tabella versione:
>      12.10.1+18.04.20180322.1-0ubuntu4 500
>         500 http://archive.ubuntu.com/ubuntu eoan/main amd64 Packages
> libappindicator3-0.1-cil-dev:
>   Installato: (nessuno)
>   Candidato:  12.10.0+git20151221-5
>   Tabella versione:
>      12.10.0+git20151221-5 500
>         500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
>

**Comment by antoniocoratelli** [comment]
ciao, scusami ho fatto un errore di copia-incolla, devi installare `libappindicator-dev`

**Comment by lesar** [comment]
sorry I do the first step (apt) but stop on second due to this sentence on site [TopIcons-plus](https://github.com/phocean/TopIcons-plus):  

> 
> WARNING
> 
>     As stated in issue #91, I have stopped maintaining this project actively.
> 
> The Gnome project chose to drop status icons and any kind of legacy tray, making the project useless on the long term and difficult to maintain due to bugs or lack of features that are out of its scope.
> 
> In particular, no wayland support can be achieved.
> 
> Open such issues not here but to the Gnome project.
> 
> Meanwhile, I encourage you to migrate to libappindicator and its extension, which is supported by most applications nowadays.

I do not think to install it on my system.

**Comment by antoniocoratelli** [comment]
Ciao lesar, ho chiuso la issue perché ho fatto del mio meglio per aiutarti a debuggare e ad avere l'indicatore, ho speso la mia serata di ieri per installarmi una VM ed ho trovato questa procedura come soluzione. 

Visto che sviluppo l'indicatore nel tempo libero principalmente per mio uso personale su Debian, non ho interesse perché supporti un ampio range di piattaforme.

Se hai voglia di entrare nel codice C++ e per farlo funzionare anche su Ubuntu 19.10 e successivi ogni contribuzione è benvenuta tramite Pull Request. 

Buona giornata

**Comment by lesar** [comment]
Ti ringrazio tanto per i vari tentativi.
Saluti,
Leonardo

Il ven 29 nov 2019, 12:27 Antonio Coratelli <notifications@github.com> ha
scritto:
