### ISSUE TITLE
Compatibility with PureOS?

### ISSUE THREAD

**Issue by tomoqv** [antoniocoratelli/bookmarks-indicator#8]
I really love this indicator and have been using it in Ubuntu 16.04 for a long while. I have now migrated one of my PCs to PureOS (Gnome) and can't get it working. Is it compatible?

**Comment by antoniocoratelli** [comment]
Hi @tomoqv , thank you for your message! 

I know that there are some issues under Gnome, but I'm confident that things can be debugged quite easily if you're willing to help me in the process.

I actually wanted to create a minimalist setup for automated builds for multiple os versions, so this sounds like a good occasion.

Are you in? :)

Best,
Antonio

**Comment by tomoqv** [comment]
Hi @antoniocoratelli , sure I'm in!
Just tell me what to do.
BR,
Tomas

**Comment by antoniocoratelli** [comment]
Great! So first of all if you have an error message when launching the indicator using the terminal please paste it here.

What PureOS version are you using?

I'll write you back as soon as  have the build system ready.

**Comment by tomoqv** [comment]
Ok, let's start with this:
```
ID=pureos
NAME=PureOS
PRETTY_NAME=PureOS

VERSION_ID=9.0
VERSION_CODENAME=amber
```
```
~$ uname -r
4.19.0-5-amd64

```
The command `~$ bookmarks-indicator` gives no output in the terminal.
I have followed the instructions on github to build the application, which gives the following if I repeat:
```
~/bookmarks-indicator/build$ sudo cmake .. && make && sudo make install
[sudo] lösenord för tomas: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tomas/bookmarks-indicator/build
Built target bookmarks-indicator
[100%] Built target bookmarks-indicator
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/bin/bookmarks-indicator

```

**Comment by tomoqv** [comment]
I have another instance of bookmarks-indicator in my Dropbox (idea of using the same cfg on all my PCs), but shouldn't be in the environment path variables, i.e. have to specify directory to launch it.

**Comment by tomoqv** [comment]
Oh, running from that build-directory yields the following:
~/bookmarks-indicator/build$ booksmarks-indicator
```
Could not find the database of available applications, run update-command-not-found as root to fix this
Sorry, command-not-found has crashed! Please file a bug report at:
http://www.debian.org/Bugs/Reporting
Please include the following information with the report:

command-not-found version: 0.3
Python version: 3.7.3 final 0
Distributor ID:	PureOS
Description:	PureOS
Release:	9.0
Codename:	amber
Exception information:

local variable 'cnf' referenced before assignment
Traceback (most recent call last):
  File "/usr/share/command-not-found/CommandNotFound/util.py", line 23, in crash_guard
    callback()
  File "/usr/lib/command-not-found", line 93, in main
    if not cnf.advise(args[0], options.ignore_installed) and not options.no_failure_msg:
UnboundLocalError: local variable 'cnf' referenced before assignment

```

**Comment by antoniocoratelli** [comment]
Hi @tomoqv , I think that the last error message you have has to do with your os, not direclty with the indicator.

Have you tried installing this Gnome extension to make the indicator work?
https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by tomoqv** [comment]
Just tried, get nothing without sudo, with sudo this:
```
No protocol specified
Unable to init server: Could not connect: Connection refused

(bookmarks-indicator:56574): Gtk-WARNING **: 06:48:02.711: cannot open display: :0

```

**Comment by antoniocoratelli** [comment]
Hi @tomoqv , I'm sorry I'm quite busy these days, I'll try to work on the issue and update you this weekend. Have a great day!

**Comment by tomoqv** [comment]
No problem, I am just grateful you're looking into this!
Thx

**Comment by antoniocoratelli** [comment]
Hi @tomoqv sorry for the long delay. Have you tried installing a gnome extension to get back support for ubuntu appindicators? 

https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by tomoqv** [comment]
Is this a different one than the one you suggested above, which I already installed? I am out travelling now, so I can't test on my PureOS machine until next week.

**Comment by antoniocoratelli** [comment]
Hi @tomoqv sorry I forgot that I already sent you that link

**Comment by antoniocoratelli** [comment]
OK, I'll install a VM to test in PureOS directly. I'm sorry for the long time it takes but I can work on the project only in my spare time

**Comment by antoniocoratelli** [comment]
Hi @tomoqv , I finally had some time to look into the issue. 

Unfortunately Gnome desktop doesn't seem to like appindicators anymore, and I couldn't find a way to make it work with Gnome extensions or other methods. 

I'm afraid that this indicator cannot support desktop environments different than XFCE :/
